spring:
  profiles:
    active: local
  ##数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.200.0.4:3306/sell?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
  #sql打印
  jpa:
    show-sql: true
##logback日志输出配置
logging:
  config: classpath:sell-logback.xml
